import type { Lesson, Achievement } from "./types"

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "first-lesson",
    name: "First Steps",
    description: "Complete your first lesson",
    icon: "🎵",
    progress: 0,
    target: 1,
  },
  {
    id: "week-streak",
    name: "Dedicated Student",
    description: "Practice for 7 days in a row",
    icon: "🔥",
    progress: 0,
    target: 7,
  },
  {
    id: "month-streak",
    name: "Committed Scholar",
    description: "Practice for 30 days in a row",
    icon: "🌟",
    progress: 0,
    target: 30,
  },
  {
    id: "rule-of-the-octave-master",
    name: "Rule of the Octave Master",
    description: "Complete all Rule of the Octave lessons",
    icon: "📐",
    progress: 0,
    target: 8,
  },
  {
    id: "schema-collector",
    name: "Schema Collector",
    description: "Learn all 18 galant schemata",
    icon: "🎼",
    progress: 0,
    target: 18,
  },
  {
    id: "diminution-expert",
    name: "Diminution Expert",
    description: "Master all historical diminution techniques",
    icon: "✨",
    progress: 0,
    target: 20,
  },
  {
    id: "german-master",
    name: "German Tradition Master",
    description: "Complete all German Griffe and patterns",
    icon: "🇩🇪",
    progress: 0,
    target: 15,
  },
  {
    id: "italian-master",
    name: "Italian Tradition Master",
    description: "Complete all Italian partimenti",
    icon: "🇮🇹",
    progress: 0,
    target: 25,
  },
  {
    id: "improviser",
    name: "Baroque Improviser",
    description: "Complete a free improvisation exercise",
    icon: "🎹",
    progress: 0,
    target: 1,
  },
  {
    id: "virtuoso",
    name: "Virtuoso",
    description: "Reach level 7 (Virtuoso)",
    icon: "👑",
    progress: 0,
    target: 1,
  },
]

export const CURRICULUM: Lesson[] = [
  // ============================================
  // LEVEL 1: FOUNDATIONS (Beginner)
  // ============================================
  {
    id: "found-1-scale-degrees",
    title: "Introduction to Scale Degrees",
    description: "Learn to think in numbers: 1, 2, 3 represent Do, Re, Mi",
    category: "foundations",
    tradition: "both",
    difficulty: "beginner",
    level: 1,
    prerequisites: [],
    xpReward: 10,
    content: {
      theory:
        "In baroque improvisation, we use numbers to represent scale degrees. 1 is the tonic (Do), 2 is the supertonic (Re), 3 is the mediant (Mi), 4 is the subdominant (Fa), 5 is the dominant (Sol), 6 is the submediant (La), 7 is the leading tone (Ti), and 8 is the octave. This system makes it easy to transpose and understand patterns in any key.",
      examples: [
        {
          id: "ex-1",
          description: "Ascending scale in C major",
          notation: "1, 2, 3, 4, 5, 6, 7, 8",
          audioPattern: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"],
        },
        {
          id: "ex-2",
          description: "Descending scale in C major",
          notation: "8, 7, 6, 5, 4, 3, 2, 1",
          audioPattern: ["C5", "B4", "A4", "G4", "F4", "E4", "D4", "C4"],
        },
      ],
      exercises: [
        {
          id: "ex1-1",
          type: "identify",
          prompt: "Listen to the scale degree and identify it",
          correctAnswer: "3",
          options: ["1", "2", "3", "4", "5"],
          audioPattern: ["E4"],
        },
        {
          id: "ex1-2",
          type: "identify",
          prompt: "Listen to the scale degree and identify it",
          correctAnswer: "5",
          options: ["3", "4", "5", "6", "7"],
          audioPattern: ["G4"],
        },
        {
          id: "ex1-3",
          type: "identify",
          prompt: "Listen to the scale degree and identify it",
          correctAnswer: "7",
          options: ["5", "6", "7", "8"],
          audioPattern: ["B4"],
        },
      ],
      historicalContext:
        "The solfège system (Do, Re, Mi) was developed by Guido of Arezzo in the 11th century and became the foundation of all musical pedagogy. In the Neapolitan conservatories, students learned to sing scale degrees before touching an instrument.",
    },
  },
  {
    id: "found-2-figured-bass-53",
    title: "Simple Figured Bass: 5/3",
    description: "Learn the most basic figured bass symbol - the root position triad",
    category: "foundations",
    tradition: "both",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-1-scale-degrees"],
    xpReward: 15,
    content: {
      theory:
        "5/3 (or just 5, or often left blank) indicates a root position triad. The numbers mean intervals above the bass: 5th and 3rd. In C major, bass note 1 with 5/3 = C-E-G. This is the most common chord and is often left unfigured.",
      examples: [
        {
          id: "ex-1",
          description: "I chord (1 with 5/3)",
          notation: "Bass: 1, Figures: 5/3",
          audioPattern: ["C3", "E4", "G4", "C5"],
          figuredBass: "5/3",
        },
        {
          id: "ex-2",
          description: "V chord (5 with 5/3)",
          notation: "Bass: 5, Figures: 5/3",
          audioPattern: ["G3", "B4", "D5", "G5"],
          figuredBass: "5/3",
        },
        {
          id: "ex-3",
          description: "IV chord (4 with 5/3)",
          notation: "Bass: 4, Figures: 5/3",
          audioPattern: ["F3", "A4", "C5", "F5"],
          figuredBass: "5/3",
        },
      ],
      exercises: [
        {
          id: "ex2-1",
          type: "identify",
          prompt: "Which bass note creates a V chord with 5/3?",
          correctAnswer: "5",
          options: ["1", "4", "5", "6"],
        },
        {
          id: "ex2-2",
          type: "identify",
          prompt: "Listen to this chord. Which bass note is it?",
          correctAnswer: "1",
          options: ["1", "4", "5"],
          audioPattern: ["C3", "E4", "G4", "C5"],
        },
        {
          id: "ex2-3",
          type: "identify",
          prompt: "What intervals are above the bass in a 5/3 chord?",
          correctAnswer: "3rd and 5th",
          options: ["3rd and 5th", "3rd and 6th", "4th and 6th", "2nd and 5th"],
        },
        {
          id: "ex2-4",
          type: "identify",
          prompt: "Listen to this chord. Is it I, IV, or V?",
          correctAnswer: "IV",
          options: ["I", "IV", "V"],
          audioPattern: ["F3", "A4", "C5", "F5"],
        },
        {
          id: "ex2-5",
          type: "identify",
          prompt: "In C major, bass note 4 with 5/3 creates which chord?",
          correctAnswer: "F-A-C (IV)",
          options: ["C-E-G (I)", "F-A-C (IV)", "G-B-D (V)", "A-C-E (vi)"],
        },
        {
          id: "ex2-6",
          type: "identify",
          prompt: "Listen to this progression. Which is it?",
          correctAnswer: "I-V-I",
          options: ["I-IV-I", "I-V-I", "IV-V-I"],
          audioPattern: ["C3", "E4", "G4", "C5", "G3", "B4", "D5", "G5", "C3", "E4", "G4", "C5"],
        },
        {
          id: "ex2-7-keyboard",
          type: "play",
          prompt: "KEYBOARD: Realize this bass line with 5/3 chords in the right hand: C-F-G-C",
          correctAnswer:
            "Play bass notes C-F-G-C with left hand, and complete triads (C-E-G, F-A-C, G-B-D, C-E-G) with right hand",
          hints: [
            "Keep your right hand in a comfortable position. Use smooth voice leading - move each voice to the nearest chord tone.",
          ],
        },
        {
          id: "ex2-8-melodic",
          type: "play",
          prompt: "MELODIES: Create a melodic line over this progression: I-IV-V-I",
          correctAnswer:
            "Improvise a melody using notes from each chord (C-E-G over I, F-A-C over IV, G-B-D over V, C-E-G over I)",
          hints: [
            "Start on C (scale degree 1), move stepwise when possible, and end on C. Use chord tones on strong beats.",
          ],
          bassPattern: "C3-F3-G3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "Figured bass (basso continuo) was the universal notation system for baroque music, allowing keyboardists to improvise harmonies from a bass line with numbers. It was invented around 1600 and remained standard practice until 1800.",
    },
  },
  {
    id: "found-3-figured-bass-63",
    title: "First Inversion: 6/3",
    description: "Learn the 6/3 chord - first inversion triad",
    category: "foundations",
    tradition: "both",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-2-figured-bass-53"],
    xpReward: 15,
    content: {
      theory:
        "6/3 (or just 6) indicates first inversion. The bass has the 3rd of the chord. In C major, bass note 3 with 6 = E-G-C. The 6/3 chord is smoother and more melodic than 5/3, perfect for stepwise bass motion.",
      examples: [
        {
          id: "ex-1",
          description: "I6 chord (3 with 6)",
          notation: "Bass: 3, Figures: 6",
          audioPattern: ["E3", "G4", "C5"],
          figuredBass: "6",
        },
        {
          id: "ex-2",
          description: "V6 chord (7 with 6)",
          notation: "Bass: 7, Figures: 6",
          audioPattern: ["B3", "D5", "G5"],
          figuredBass: "6",
        },
        {
          id: "ex-3",
          description: "IV6 chord (6 with 6)",
          notation: "Bass: 6, Figures: 6",
          audioPattern: ["A3", "C5", "F5"],
          figuredBass: "6",
        },
      ],
      exercises: [
        {
          id: "ex3-1",
          type: "identify",
          prompt: "Which bass note creates a I6 chord?",
          correctAnswer: "3",
          options: ["1", "2", "3", "4", "5"],
        },
        {
          id: "ex3-2",
          type: "identify",
          prompt: "Listen to this chord. Is it in root position (5/3) or first inversion (6)?",
          correctAnswer: "First inversion (6)",
          options: ["Root position (5/3)", "First inversion (6)"],
          audioPattern: ["E3", "G4", "C5"],
        },
        {
          id: "ex3-3",
          type: "identify",
          prompt: "What intervals are above the bass in a 6/3 chord?",
          correctAnswer: "3rd and 6th",
          options: ["3rd and 5th", "3rd and 6th", "4th and 6th", "2nd and 6th"],
        },
        {
          id: "ex3-4",
          type: "identify",
          prompt: "Listen to this chord. Which bass note is it?",
          correctAnswer: "7",
          options: ["5", "6", "7", "1"],
          audioPattern: ["B3", "D5", "G5"],
        },
        {
          id: "ex3-5",
          type: "identify",
          prompt: "Why is 6/3 smoother than 5/3 for stepwise bass motion?",
          correctAnswer: "The bass moves by step, not leap",
          options: [
            "The bass moves by step, not leap",
            "It has more notes",
            "It's louder",
            "It's in a higher register",
          ],
        },
        {
          id: "ex3-6",
          type: "identify",
          prompt: "Listen to this progression. Which is it?",
          correctAnswer: "I-I6-V",
          options: ["I-IV-V", "I-I6-V", "I-V-I"],
          audioPattern: ["C3", "E4", "G4", "C5", "E3", "G4", "C5", "G3", "B4", "D5"],
        },
        {
          id: "ex3-7-keyboard",
          type: "play",
          prompt: "KEYBOARD: Realize this ascending bass line with 6/3 chords: C-D-E-F (figures: - 6 6 -)",
          correctAnswer: "Play bass C-D-E-F with left hand, right hand plays: C-E-G, D-F-A, E-G-C, F-A-C",
          hints: [
            "The 6/3 chords create smooth stepwise motion. Keep the right hand close together, moving each voice by step when possible.",
          ],
        },
        {
          id: "ex3-8-melodic",
          type: "play",
          prompt: "MELODIES: Create a melodic line over this bass: C-D-E-F (I-ii6-I6-IV)",
          correctAnswer:
            "Improvise a melody using chord tones, emphasizing stepwise motion to match the smooth bass line",
          hints: [
            "Try starting on G (5), moving to F (over D), E (over E), then C or F (over F). Stepwise motion works beautifully with 6/3 chords.",
          ],
          bassPattern: "C3-D3-E3-F3",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "First inversion chords (6/3) were essential for creating smooth, stepwise bass lines in baroque music. The Rule of the Octave uses 6/3 chords on scale degrees 2, 3, 6, and 7 ascending.",
    },
  },
  {
    id: "found-4-figured-bass-64",
    title: "Second Inversion: 6/4",
    description: "Learn the 6/4 chord - second inversion triad",
    category: "foundations",
    tradition: "both",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-3-figured-bass-63"],
    xpReward: 15,
    content: {
      theory:
        "6/4 indicates second inversion. The bass has the 5th of the chord. In C major, bass note 5 with 6/4 = G-C-E. The 6/4 is unstable and usually resolves to 5/3. The most important use is the cadential 6/4: I6/4 on a strong beat resolves to V on the next beat, creating a powerful cadence.",
      examples: [
        {
          id: "ex-1",
          description: "Cadential 6/4 (I6/4 resolving to V)",
          notation: "Bass: 5-5, Figures: 6/4-5/3",
          audioPattern: ["G3", "C5", "E5", "G3", "B4", "D5"],
          figuredBass: "6/4-5/3",
        },
        {
          id: "ex-2",
          description: "Passing 6/4 (between I and I6)",
          notation: "Bass: 1-2-3, Figures: 5/3-6/4-6",
          audioPattern: ["C3", "E4", "G4", "D3", "F4", "A4", "E3", "G4", "C5"],
          figuredBass: "5/3-6/4-6",
        },
        {
          id: "ex-3",
          description: "Pedal 6/4 (over sustained bass)",
          notation: "Bass: 1-1-1, Figures: 5/3-6/4-5/3",
          audioPattern: ["C3", "E4", "G4", "C3", "F4", "A4", "C3", "E4", "G4"],
          figuredBass: "5/3-6/4-5/3",
        },
      ],
      exercises: [
        {
          id: "ex4-1",
          type: "identify",
          prompt: "What intervals are above the bass in a 6/4 chord?",
          correctAnswer: "4th and 6th",
          options: ["3rd and 5th", "3rd and 6th", "4th and 6th", "2nd and 6th"],
        },
        {
          id: "ex4-2",
          type: "identify",
          prompt: "Listen to this cadential 6/4. What does it resolve to?",
          correctAnswer: "V (5/3)",
          options: ["I (5/3)", "V (5/3)", "IV (5/3)", "vi (5/3)"],
          audioPattern: ["G3", "C5", "E5", "G3", "B4", "D5"],
        },
        {
          id: "ex4-3",
          type: "identify",
          prompt: "Why is the 6/4 chord considered unstable?",
          correctAnswer: "The 4th above a bass was traditionally considered a dissonance",
          options: [
            "It has too many notes",
            "The 4th above a bass was traditionally considered a dissonance",
            "It's too high",
            "It's too quiet",
          ],
        },
        {
          id: "ex4-4",
          type: "identify",
          prompt: "In a cadential 6/4, which bass note is most common?",
          correctAnswer: "5 (dominant)",
          options: ["1 (tonic)", "4 (subdominant)", "5 (dominant)", "6 (submediant)"],
        },
        {
          id: "ex4-5",
          type: "identify",
          prompt: "Listen to this progression. Which type of 6/4 is it?",
          correctAnswer: "Passing 6/4",
          options: ["Cadential 6/4", "Passing 6/4", "Pedal 6/4"],
          audioPattern: ["C3", "E4", "G4", "D3", "F4", "A4", "E3", "G4", "C5"],
        },
        {
          id: "ex4-6",
          type: "identify",
          prompt: "In C major, bass note 5 with 6/4 creates which notes?",
          correctAnswer: "G-C-E",
          options: ["C-E-G", "E-G-C", "G-C-E", "G-B-D"],
        },
        {
          id: "ex4-7-keyboard",
          type: "play",
          prompt: "KEYBOARD: Realize a cadential 6/4: Bass G-G (figures: 6/4-5/3), then resolve to C",
          correctAnswer:
            "Play bass G in bass twice, right hand plays C-E-G (6/4) then B-D-G (5/3), then resolve to C-E-G over bass C",
          hints: [
            "The 6/4 chord (C-E over bass G) resolves down by step: C→B and E→D, creating the V chord before final resolution to I.",
          ],
        },
        {
          id: "ex4-8-melodic",
          type: "play",
          prompt: "MELODIES: Create a melodic cadence using the cadential 6/4 pattern",
          correctAnswer:
            "Improvise a melody that emphasizes the resolution: use C or E over the first G (6/4), resolve to B or D over the second G (V), then end on C",
          hints: [
            "Try: E (over G 6/4) → D (over G V) → C (over C I). The stepwise descent creates a strong cadential feeling.",
          ],
          bassPattern: "G3-G3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "The cadential 6/4 is one of the most important patterns in baroque music. It appears in virtually every piece and was one of the first patterns taught to students. The 6/4 chord's instability (due to the dissonant 4th above the bass) and need for resolution makes it perfect for creating strong cadences.",
    },
  },
  {
    id: "found-5-three-cadences",
    title: "The Three Partimenti Cadences",
    description: "Master Simple, Compound, and Double cadences (Neapolitan tradition)",
    category: "foundations",
    tradition: "italian",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-4-figured-bass-64"],
    xpReward: 20,
    content: {
      theory:
        "Cadences are classified by how long the dominant lasts. The THREE BASIC CADENCES are: (1) SIMPLE CADENCE (Cadenza Semplice): dominant lasts ONE BAR (4 beats) with a single sonority (5/3 or 7/3). (2) COMPOUND CADENCE (Cadenza Composta): dominant lasts TWO BARS (8 beats) with two sonorities, often including a 4-3 suspension. (3) DOUBLE CADENCE (Cadenza Doppia): dominant lasts FOUR BARS (16 beats) with four successive sonorities above V: 5/3 (or 7/3), 6/4, 5/4, and 5/3 (or 7/3). These cadences are the foundation of all baroque music and must be memorized in all keys.",
      examples: [
        {
          id: "ex-1",
          description: "Simple Cadence (Cadenza Semplice) - V lasts 1 bar (4 beats)",
          notation: "Bass: 5-1, Figures: 7/3-5/3 (or 5/3-5/3)",
          audioPattern: ["G3", "B4", "D5", "F5", "C3", "E4", "G4", "C5"],
          figuredBass: "7/3-5/3",
        },
        {
          id: "ex-2",
          description: "Compound Cadence (Cadenza Composta) - V lasts 2 bars (8 beats) with 4-3 suspension",
          notation: "Bass: 5-5-1, Figures: 5/4-5/3-5/3",
          audioPattern: ["G3", "C5", "D5", "G3", "B4", "D5", "C3", "E4", "G4", "C5"],
          figuredBass: "5/4-5/3-5/3",
        },
        {
          id: "ex-3",
          description: "Double Cadence (Cadenza Doppia) - V lasts 4 bars (16 beats) with four sonorities",
          notation: "Bass: 5-5-5-5-1, Figures: 5/3-6/4-5/4-5/3-5/3",
          audioPattern: [
            "G3",
            "B4",
            "D5",
            "G3",
            "C5",
            "E5",
            "G3",
            "C5",
            "D5",
            "G3",
            "B4",
            "D5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
          figuredBass: "5/3-6/4-5/4-5/3-5/3",
        },
        {
          id: "ex-4",
          description: "Double Cadence with I-V-I bass (alternative form)",
          notation: "Bass: 1-5-5-5-5-1, Figures: 5/3-5/3-6/4-5/4-7/3-5/3",
          audioPattern: [
            "C3",
            "E4",
            "G4",
            "G3",
            "B4",
            "D5",
            "G3",
            "C5",
            "E5",
            "G3",
            "C5",
            "D5",
            "G3",
            "B4",
            "D5",
            "F5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
          figuredBass: "5/3-5/3-6/4-5/4-7/3-5/3",
        },
      ],
      exercises: [
        {
          id: "ex5-1",
          type: "identify",
          prompt: "Listen to this cadence. How many bars does the dominant last?",
          correctAnswer: "1 bar (Simple Cadence)",
          options: ["1 bar (Simple Cadence)", "2 bars (Compound Cadence)", "4 bars (Double Cadence)"],
          audioPattern: ["G3", "B4", "D5", "F5", "C3", "E4", "G4", "C5"],
        },
        {
          id: "ex5-2",
          type: "identify",
          prompt: "Listen to this cadence. Which type is it?",
          correctAnswer: "Compound Cadence",
          options: ["Simple Cadence", "Compound Cadence", "Double Cadence"],
          audioPattern: ["G3", "C5", "D5", "G3", "B4", "D5", "C3", "E4", "G4", "C5"],
        },
        {
          id: "ex5-3",
          type: "identify",
          prompt: "Listen to this cadence. Which type is it?",
          correctAnswer: "Double Cadence",
          options: ["Simple Cadence", "Compound Cadence", "Double Cadence"],
          audioPattern: [
            "G3",
            "B4",
            "D5",
            "G3",
            "C5",
            "E5",
            "G3",
            "C5",
            "D5",
            "G3",
            "B4",
            "D5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
        },
        {
          id: "ex5-4",
          type: "identify",
          prompt: "In a Compound Cadence, what suspension is typically used?",
          correctAnswer: "4-3 suspension",
          options: ["2-3 suspension", "4-3 suspension", "7-6 suspension", "9-8 suspension"],
        },
        {
          id: "ex5-5",
          type: "identify",
          prompt: "In a Double Cadence, what are the four sonorities above the dominant?",
          correctAnswer: "5/3, 6/4, 5/4, 5/3",
          options: ["5/3, 6/3, 5/3, 5/3", "5/3, 6/4, 5/4, 5/3", "6/3, 6/4, 5/3, 5/3", "5/3, 5/3, 5/3, 5/3"],
        },
        {
          id: "ex5-6",
          type: "identify",
          prompt: "Which cadence is the most elaborate and takes the longest time?",
          correctAnswer: "Double Cadence (Cadenza Doppia)",
          options: [
            "Simple Cadence (Cadenza Semplice)",
            "Compound Cadence (Cadenza Composta)",
            "Double Cadence (Cadenza Doppia)",
          ],
        },
        {
          id: "ex5-7-keyboard",
          type: "play",
          prompt:
            "KEYBOARD: Realize a Simple Cadence in C major. Bass: G-C with figures 7/3-5/3. Play the dominant seventh (G-B-D-F) resolving to tonic (C-E-G-C).",
          correctAnswer: "Correct realization with proper voice leading: F→E, D→C, B→C",
          hints: [
            "The seventh (F) must resolve down by step to E. Keep common tones where possible. The leading tone (B) resolves up to C.",
          ],
        },
        {
          id: "ex5-8-keyboard",
          type: "play",
          prompt:
            "KEYBOARD: Realize a Compound Cadence in C major. Bass: G-G-C with figures 5/4-5/3-5/3. The 4-3 suspension creates the compound effect.",
          correctAnswer: "Correct realization: G-C-D over first G, G-B-D over second G (C resolves to B), then C-E-G-C",
          hints: [
            "The C is prepared, suspended over the second G (creating the 4th), then resolved down to B (the 3rd). This is the characteristic 4-3 suspension of the Compound Cadence.",
          ],
        },
        {
          id: "ex5-9-keyboard",
          type: "play",
          prompt:
            "KEYBOARD: Realize a Double Cadence in C major. Bass: G-G-G-G-C with figures 5/3-6/4-5/4-7/3-5/3. This is the most elaborate cadence.",
          correctAnswer: "Correct realization with all four sonorities: G-B-D, G-C-E, G-C-D, G-B-D-F, then C-E-G-C",
          hints: [
            "Each sonority lasts one beat. The 6/4 (C-E over G) is the cadential 6/4 we learned earlier. It resolves through 5/4 (C-D) to 7/3 (B-D-F) before final resolution to I.",
          ],
        },
        {
          id: "ex5-10-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a melodic line over a Simple Cadence. The bass plays G (1 bar) then C (1 bar). Your melody should emphasize the resolution.",
          correctAnswer: "Melodic line using chord tones, emphasizing the resolution from V to I",
          hints: [
            "Try: D (over G) → C (over C), or F (over G) → E (over C). The stepwise descent creates a strong cadential feeling. You can also use B → C for the leading tone resolution.",
          ],
          bassPattern: "G3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
        {
          id: "ex5-11-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a melodic line over a Compound Cadence. The bass plays G (2 bars) then C (1 bar). Use the 4-3 suspension in your melody.",
          correctAnswer: "Melodic line featuring a 4-3 suspension (C→B) over the dominant",
          hints: [
            "Try: C (over first G, held for 2 bars) → B (over second G) → C (over C). This creates the characteristic 4-3 suspension of the Compound Cadence. The C is prepared, suspended, then resolved down to B.",
          ],
          bassPattern: "G3-G3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
        {
          id: "ex5-12-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a melodic line over a Double Cadence. The bass plays G (4 bars) then C (1 bar). Your melody should elaborate the four sonorities.",
          correctAnswer: "Melodic line that follows the four sonorities: 5/3, 6/4, 5/4, 7/3, then resolves to I",
          hints: [
            "Try: D (bar 1) → E (bar 2) → D (bar 3) → D or F (bar 4) → C (final). This follows the harmonic progression while creating a melodic line. You can also try: B → C → B → B → C for a simpler approach.",
          ],
          bassPattern: "G3-G3-G3-G3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "These three cadences are the foundation of Neapolitan pedagogy. Fenaroli wrote: 'Before attempting any partimento, the student must know the three cadences perfectly in all keys.' The Simple, Compound, and Double cadences appear in every baroque composition and were the first patterns memorized by students at the conservatories. The Double Cadence (Cadenza Doppia) is particularly important as it combines elements from both Simple and Compound cadences, creating the most elaborate and satisfying resolution in baroque music.",
    },
  },
  {
    id: "found-6-rule-octave-asc-1",
    title: "Rule of the Octave - Ascending (1-4)",
    description: "Learn degrees 1-4 ascending with proper harmonization",
    category: "foundations",
    tradition: "italian",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-5-three-cadences"],
    xpReward: 25,
    content: {
      theory:
        "The Rule of the Octave is THE fundamental pattern of baroque harmony - every student must memorize it in all keys. We'll learn it progressively: STAGE 1: Start with ALL parallel 6/3 chords (simplest). STAGE 2: Add 5/3 on scale degrees 1 and 5 (tonic and dominant). STAGE 3: Full Rule. Ascending 1-4: 1(5/3), 2(6/3), 3(6/3), 4(5/3 or 6/3). The bass moves stepwise, and the 6/3 chords create smooth voice leading.",
      examples: [
        {
          id: "ex-1",
          description: "Stage 1: All parallel 6/3 chords (C-D-E-F)",
          notation: "Bass: 1-2-3-4 (C-D-E-F), Figures: 6-6-6-6",
          audioPattern: ["C3", "E4", "G4", "D3", "F4", "A4", "E3", "G4", "C5", "F3", "A4", "C5"],
          figuredBass: "6-6-6-6",
        },
        {
          id: "ex-2",
          description: "Stage 2: Add 5/3 on scale degree 1 (C-D-E-F)",
          notation: "Bass: 1-2-3-4 (C-D-E-F), Figures: 5/3-6-6-6",
          audioPattern: ["C3", "E4", "G4", "C5", "D3", "F4", "A4", "E3", "G4", "C5", "F3", "A4", "C5"],
          figuredBass: "5/3-6-6-6",
        },
        {
          id: "ex-3",
          description: "Stage 3: Full Rule ascending 1-4 (C-D-E-F)",
          notation: "Bass: 1-2-3-4 (C-D-E-F), Figures: 5/3-6-6-5/3",
          audioPattern: ["C3", "E4", "G4", "C5", "D3", "F4", "A4", "E3", "G4", "C5", "F3", "A4", "C5", "F5"],
          figuredBass: "5/3-6-6-5/3",
        },
      ],
      exercises: [
        {
          id: "ex6-1",
          type: "identify",
          prompt: "Listen to this ascending bass (C-D-E-F). Which stage is it?",
          correctAnswer: "Stage 1: All parallel 6/3",
          options: ["Stage 1: All parallel 6/3", "Stage 2: 5/3 on 1", "Stage 3: Full Rule"],
          audioPattern: ["C3", "E4", "G4", "D3", "F4", "A4", "E3", "G4", "C5", "F3", "A4", "C5"],
        },
        {
          id: "ex6-2",
          type: "identify",
          prompt: "In the full Rule, which scale degrees get 5/3 chords in the ascending 1-4 pattern?",
          correctAnswer: "1 and 4",
          options: ["1 and 2", "1 and 4", "2 and 3", "All of them"],
        },
        {
          id: "ex6-3",
          type: "identify",
          prompt: "Why do we start with all parallel 6/3 chords?",
          correctAnswer: "It's the simplest and creates smooth voice leading",
          options: [
            "It's the simplest and creates smooth voice leading",
            "It sounds better",
            "It's louder",
            "It's traditional",
          ],
        },
        {
          id: "ex6-4",
          type: "identify",
          prompt: "Listen to this progression. Is it Stage 1, 2, or 3?",
          correctAnswer: "Stage 3: Full Rule",
          options: ["Stage 1: All parallel 6/3", "Stage 2: 5/3 on 1", "Stage 3: Full Rule"],
          audioPattern: ["C3", "E4", "G4", "C5", "D3", "F4", "A4", "E3", "G4", "C5", "F3", "A4", "C5", "F5"],
        },
        {
          id: "ex6-5-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play Stage 1 (all parallel 6/3) ascending C-D-E-F",
          correctAnswer: "Bass C-D-E-F, right hand plays 6/3 chords: C-E-G, D-F-A, E-G-C, F-A-C",
          hints: [
            "Keep the right hand close together. Each chord is a 6/3 inversion. Move each voice by step when possible.",
          ],
        },
        {
          id: "ex6-6-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play Stage 3 (Full Rule) ascending C-D-E-F with figures 5/3-6-6-5/3",
          correctAnswer: "Bass C-D-E-F, right hand: C-E-G-C (5/3), D-F-A (6), E-G-C (6), F-A-C-F (5/3)",
          hints: [
            "Start with root position on C (5/3), then 6/3 on D and E, then root position on F (5/3). Smooth voice leading throughout.",
          ],
        },
        {
          id: "ex6-7-melodic",
          type: "play",
          prompt: "MELODIES: Create a melodic line over ascending bass C-D-E-F (Stage 3: Full Rule)",
          correctAnswer: "Melodic line using chord tones, emphasizing stepwise motion",
          hints: [
            "Try: C (over C) → D (over D) → E (over E) → F (over F) for a simple ascending line. Or: G (over C) → F (over D) → E (over E) → F (over F) for more variety.",
          ],
          bassPattern: "C3-D3-E3-F3",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "First codified by François Campion (1716), the Rule of the Octave became the foundation of all baroque keyboard training. Every student memorized this pattern in all keys. The progressive approach (starting with parallel 6/3 chords) is pedagogically sound, allowing students to build complexity gradually.",
    },
  },
  {
    id: "found-7-rule-octave-asc-2",
    title: "Rule of the Octave - Ascending (5-8)",
    description: "Complete the ascending Rule with degrees 5-8",
    category: "foundations",
    tradition: "italian",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-6-rule-octave-asc-1"],
    xpReward: 25,
    content: {
      theory:
        "Ascending continued: 5(5/3), 6(6/3 or 5/3), 7(6/3 or 6/5/3), 8(5/3). The dominant (5) and tonic (8) are ALWAYS 5/3 (root position). Scale degree 6 can be either 6/3 or 5/3 depending on context. Scale degree 7 (leading tone) is typically 6/3, but can be 6/5/3 (diminished seventh) for more tension. Now you know the complete ascending Rule of the Octave!",
      examples: [
        {
          id: "ex-1",
          description: "Full ascending Rule (C-D-E-F-G-A-B-C)",
          notation: "Bass: 1-2-3-4-5-6-7-8, Figures: 5/3-6-6-5/3-5/3-6-6-5/3",
          audioPattern: [
            "C3",
            "E4",
            "G4",
            "C5",
            "D3",
            "F4",
            "A4",
            "E3",
            "G4",
            "C5",
            "F3",
            "A4",
            "C5",
            "F5",
            "G3",
            "B4",
            "D5",
            "G5",
            "A3",
            "C5",
            "E5",
            "B3",
            "D5",
            "F5",
            "C4",
            "E5",
            "G5",
            "C6",
          ],
          figuredBass: "5/3-6-6-5/3-5/3-6-6-5/3",
        },
        {
          id: "ex-2",
          description: "Ascending 5-8 with alternative 6 (G-A-B-C)",
          notation: "Bass: 5-6-7-8, Figures: 5/3-5/3-6-5/3",
          audioPattern: ["G3", "B4", "D5", "G5", "A3", "C5", "E5", "A5", "B3", "D5", "F5", "C4", "E5", "G5", "C6"],
          figuredBass: "5/3-5/3-6-5/3",
        },
        {
          id: "ex-3",
          description: "Ascending 5-8 with diminished seventh on 7 (G-A-B-C)",
          notation: "Bass: 5-6-7-8, Figures: 5/3-6-6/5/3-5/3",
          audioPattern: ["G3", "B4", "D5", "G5", "A3", "C5", "E5", "B3", "D5", "F5", "Ab5", "C4", "E5", "G5", "C6"],
          figuredBass: "5/3-6-6/5/3-5/3",
        },
      ],
      exercises: [
        {
          id: "ex7-1",
          type: "identify",
          prompt: "Which scale degrees ALWAYS get 5/3 chords in the ascending Rule?",
          correctAnswer: "1, 5, and 8",
          options: ["1, 4, and 5", "1, 5, and 8", "All of them", "None of them"],
        },
        {
          id: "ex7-2",
          type: "identify",
          prompt: "Listen to the complete ascending Rule. How many 5/3 chords are there?",
          correctAnswer: "4 (on 1, 4, 5, 8)",
          options: ["2", "3", "4 (on 1, 4, 5, 8)", "5"],
          audioPattern: [
            "C3",
            "E4",
            "G4",
            "C5",
            "D3",
            "F4",
            "A4",
            "E3",
            "G4",
            "C5",
            "F3",
            "A4",
            "C5",
            "F5",
            "G3",
            "B4",
            "D5",
            "G5",
            "A3",
            "C5",
            "E5",
            "B3",
            "D5",
            "F5",
            "C4",
            "E5",
            "G5",
            "C6",
          ],
        },
        {
          id: "ex7-3",
          type: "identify",
          prompt: "What is the alternative figure for scale degree 6?",
          correctAnswer: "5/3 (instead of 6)",
          options: ["6/4", "5/3 (instead of 6)", "7", "4/3"],
        },
        {
          id: "ex7-4",
          type: "identify",
          prompt: "What does 6/5/3 on scale degree 7 create?",
          correctAnswer: "Diminished seventh chord",
          options: ["Major seventh", "Diminished seventh chord", "Augmented sixth", "Dominant seventh"],
        },
        {
          id: "ex7-5-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play the complete ascending Rule of the Octave in C major (C-D-E-F-G-A-B-C)",
          correctAnswer: "Correct realization with proper figures: 5/3-6-6-5/3-5/3-6-6-5/3",
          hints: [
            "Remember: 5/3 on 1, 4, 5, 8. All others are 6/3. Keep smooth voice leading throughout. This is the most important pattern in baroque music!",
          ],
        },
        {
          id: "ex7-6-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play ascending 5-8 (G-A-B-C) with the alternative 5/3 on scale degree 6",
          correctAnswer: "Bass G-A-B-C, figures 5/3-5/3-6-5/3",
          hints: [
            "Both G and A get root position (5/3) chords. This creates a stronger harmonic progression than using 6/3 on A.",
          ],
        },
        {
          id: "ex7-7-melodic",
          type: "play",
          prompt: "MELODIES: Create a melodic line over the complete ascending Rule (C-D-E-F-G-A-B-C)",
          correctAnswer: "Melodic line following the harmonic progression, emphasizing stepwise motion",
          hints: [
            "Try starting on C and ascending to the octave C, using chord tones on each bass note. Or create a more elaborate line with passing tones and neighbor notes.",
          ],
          bassPattern: "C3-D3-E3-F3-G3-A3-B3-C4",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "The complete ascending Rule of the Octave was memorized by every baroque musician. It appears in thousands of compositions and was the foundation for improvisation. The progressive approach emphasizes mastering the simple version first, then adding nuances gradually.",
    },
  },
  {
    id: "found-8-rule-octave-desc",
    title: "Rule of the Octave - Descending",
    description: "Learn the descending Rule with different harmonizations",
    category: "foundations",
    tradition: "italian",
    difficulty: "beginner",
    level: 1,
    prerequisites: ["found-7-rule-octave-asc-2"],
    xpReward: 30,
    content: {
      theory:
        "Descending: 8(5/3), 7(6/3), 6(6/3), 5(5/3), 4(6/3), 3(6/3), 2(7/5/3 or 6/5), 1(5/3). IMPORTANT: Scale degree 2 descending uses 7/5/3 (dominant seventh chord), different from ascending! This creates stronger harmonic motion toward the tonic. The descending Rule has more 6/3 chords than the ascending, creating smooth stepwise voice leading. You must memorize BOTH ascending and descending Rules in ALL keys.",
      examples: [
        {
          id: "ex-1",
          description: "Full descending Rule (C-B-A-G-F-E-D-C)",
          notation: "Bass: 8-7-6-5-4-3-2-1, Figures: 5/3-6-6-5/3-6-6-7/5/3-5/3",
          audioPattern: [
            "C4",
            "E5",
            "G5",
            "C6",
            "B3",
            "D5",
            "F5",
            "A3",
            "C5",
            "E5",
            "G3",
            "B4",
            "D5",
            "G5",
            "F3",
            "A4",
            "C5",
            "E3",
            "G4",
            "C5",
            "D3",
            "F4",
            "A4",
            "C5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
          figuredBass: "5/3-6-6-5/3-6-6-7/5/3-5/3",
        },
        {
          id: "ex-2",
          description: "Descending with alternative 6/5 on scale degree 2 (C-B-A-G-F-E-D-C)",
          notation: "Bass: 8-7-6-5-4-3-2-1, Figures: 5/3-6-6-5/3-6-6-6/5-5/3",
          audioPattern: [
            "C4",
            "E5",
            "G5",
            "C6",
            "B3",
            "D5",
            "F5",
            "A3",
            "C5",
            "E5",
            "G3",
            "B4",
            "D5",
            "G5",
            "F3",
            "A4",
            "C5",
            "E3",
            "G4",
            "C5",
            "D3",
            "F4",
            "B4",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
          figuredBass: "5/3-6-6-5/3-6-6-6/5-5/3",
        },
        {
          id: "ex-3",
          description: "Descending 5-1 (G-F-E-D-C)",
          notation: "Bass: 5-4-3-2-1, Figures: 5/3-6-6-7/5/3-5/3",
          audioPattern: [
            "G3",
            "B4",
            "D5",
            "G5",
            "F3",
            "A4",
            "C5",
            "E3",
            "G4",
            "C5",
            "D3",
            "F4",
            "A4",
            "C5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
          figuredBass: "5/3-6-6-7/5/3-5/3",
        },
      ],
      exercises: [
        {
          id: "ex8-1",
          type: "identify",
          prompt: "What is the KEY DIFFERENCE between ascending and descending on scale degree 2?",
          correctAnswer: "Descending uses 7/5/3 (dominant seventh), ascending uses 6",
          options: [
            "Descending uses 7/5/3 (dominant seventh), ascending uses 6",
            "They're the same",
            "Descending uses 6/4",
            "Descending uses 5/3",
          ],
        },
        {
          id: "ex8-2",
          type: "identify",
          prompt: "Listen to this descending Rule. How many 5/3 chords are there?",
          correctAnswer: "3 (on 8, 5, 1)",
          options: ["2", "3 (on 8, 5, 1)", "4", "5"],
          audioPattern: [
            "C4",
            "E5",
            "G5",
            "C6",
            "B3",
            "D5",
            "F5",
            "A3",
            "C5",
            "E5",
            "G3",
            "B4",
            "D5",
            "G5",
            "F3",
            "A4",
            "C5",
            "E3",
            "G4",
            "C5",
            "D3",
            "F4",
            "A4",
            "C5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
        },
        {
          id: "ex8-3",
          type: "identify",
          prompt: "Why does scale degree 2 descending use 7/5/3?",
          correctAnswer: "It creates stronger harmonic motion toward the tonic (V7-I)",
          options: [
            "It sounds better",
            "It creates stronger harmonic motion toward the tonic (V7-I)",
            "It's easier to play",
            "It's traditional",
          ],
        },
        {
          id: "ex8-4",
          type: "identify",
          prompt: "Which scale degrees get 6/3 chords in the descending Rule?",
          correctAnswer: "7, 6, 4, 3",
          options: ["All of them", "7, 6, 4, 3", "2, 3, 4", "None of them"],
        },
        {
          id: "ex8-5",
          type: "identify",
          prompt: "Listen to this progression. Is it ascending or descending?",
          correctAnswer: "Descending",
          options: ["Ascending", "Descending"],
          audioPattern: [
            "C4",
            "E5",
            "G5",
            "C6",
            "B3",
            "D5",
            "F5",
            "A3",
            "C5",
            "E5",
            "G3",
            "B4",
            "D5",
            "G5",
            "F3",
            "A4",
            "C5",
            "E3",
            "G4",
            "C5",
            "D3",
            "F4",
            "A4",
            "C5",
            "C3",
            "E4",
            "G4",
            "C5",
          ],
        },
        {
          id: "ex8-6-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play the complete descending Rule of the Octave in C major (C-B-A-G-F-E-D-C)",
          correctAnswer: "Correct realization with proper figures: 5/3-6-6-5/3-6-6-7/5/3-5/3",
          hints: [
            "Remember: 5/3 on 8, 5, 1. Scale degree 2 gets 7/5/3 (dominant seventh). All others are 6/3. The dominant seventh on 2 creates a strong pull to the tonic.",
          ],
        },
        {
          id: "ex8-7-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play descending 5-1 (G-F-E-D-C) emphasizing the V7-I cadence",
          correctAnswer: "Bass G-F-E-D-C, figures 5/3-6-6-7/5/3-5/3",
          hints: [
            "The 7/5/3 on D (scale degree 2) is a dominant seventh chord (D-F-A-C) that resolves strongly to the tonic C. This is the foundation of all baroque cadences.",
          ],
        },
        {
          id: "ex8-8-melodic",
          type: "play",
          prompt: "MELODIES: Create a melodic line over the complete descending Rule (C-B-A-G-F-E-D-C)",
          correctAnswer: "Melodic line following the harmonic progression, emphasizing the descent",
          hints: [
            "Try starting on C and descending to the lower C, using chord tones. Or create a more elaborate line that moves contrary to the bass (ascending while the bass descends).",
          ],
          bassPattern: "C4-B3-A3-G3-F3-E3-D3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
        {
          id: "ex8-9-keyboard",
          type: "play",
          prompt: "KEYBOARD: Play BOTH ascending and descending Rules back-to-back (C up to C, then C down to C)",
          correctAnswer: "Complete ascending then descending Rule with proper figures",
          hints: [
            "This is the ultimate test! Ascending: 5/3-6-6-5/3-5/3-6-6-5/3. Descending: 5/3-6-6-5/3-6-6-7/5/3-5/3. Practice this in all keys until it's automatic.",
          ],
        },
      ],
      historicalContext:
        "The descending Rule of the Octave completes your foundation in baroque harmony. Fenaroli wrote: 'The student who knows the Rule of the Octave in all keys, ascending and descending, possesses the key to all harmony.' This pattern appears in virtually every baroque composition. The use of 7/5/3 on scale degree 2 descending (creating V7-I) is one of the most important harmonic progressions in all of Western music. Daily practice of the Rule in all keys is the foundation of improvisational fluency.",
    },
  },

  // ============================================
  // LEVEL 2: BASIC PATTERNS (Elementary)
  // ============================================
  {
    id: "basic-1-simple-suspensions",
    title: "Simple Suspensions: 4-3",
    description: "Learn the most common suspension pattern",
    category: "patterns",
    tradition: "both",
    difficulty: "elementary",
    level: 2,
    prerequisites: ["found-8-rule-octave-desc"],
    xpReward: 30,
    content: {
      theory:
        "A suspension is a dissonance created by DELAYING the resolution of a note. The 4-3 suspension is the most common and important suspension in baroque music. THREE STAGES: (1) PREPARATION: The 4th appears as a consonance in the previous chord. (2) SUSPENSION: The bass moves, but the upper voice HOLDS the same note, creating a dissonant 4th above the new bass. (3) RESOLUTION: The suspended note resolves DOWN BY STEP to the 3rd. The 4-3 suspension creates tension and release, making cadences more expressive. It appears in the Compound Cadence and throughout baroque music. RULE: The suspended note must be TIED or held from the previous beat - it cannot be re-struck.",
      examples: [
        {
          id: "ex-1",
          description: "Simple 4-3 suspension over V-I (G-C)",
          notation: "Bass: G-C, Upper voice: C (held) - B, Figures: 4-3",
          audioPattern: ["G3", "C5", "D5", "C3", "B4", "E5"],
          figuredBass: "4-3",
        },
        {
          id: "ex-2",
          description: "4-3 suspension in Compound Cadence",
          notation: "Bass: G-G-C, Figures: 5/4-5/3-5/3",
          audioPattern: ["G3", "C5", "D5", "G3", "B4", "D5", "C3", "E4", "G4", "C5"],
          figuredBass: "5/4-5/3-5/3",
        },
        {
          id: "ex-3",
          description: "Chain of 4-3 suspensions (sequence)",
          notation: "Bass: C-D-E-F, Figures: 5/3-4/3-4/3-5/3",
          audioPattern: ["C3", "E4", "G4", "C5", "D3", "G4", "A4", "E3", "A4", "B4", "F3", "A4", "C5", "F5"],
          figuredBass: "5/3-4/3-4/3-5/3",
        },
        {
          id: "ex-4",
          description: "4-3 suspension with seventh (9-8 4-3)",
          notation: "Bass: F-G-C, Figures: 9-8 4-3 5/3",
          audioPattern: ["F3", "D5", "C5", "G3", "C5", "B4", "C3", "E4", "G4", "C5"],
          figuredBass: "9-8 4-3 5/3",
        },
      ],
      exercises: [
        {
          id: "ex-susp-1",
          type: "identify",
          prompt: "Listen to this suspension. Which type is it?",
          correctAnswer: "4-3 suspension",
          options: ["4-3 suspension", "7-6 suspension", "9-8 suspension", "2-3 suspension"],
          audioPattern: ["G3", "C5", "D5", "C3", "B4", "E5"],
        },
        {
          id: "ex-susp-2",
          type: "identify",
          prompt: "In a 4-3 suspension, which direction does the suspended note resolve?",
          correctAnswer: "Down by step",
          options: ["Down by step", "Up by step", "Down by leap", "Up by leap"],
        },
        {
          id: "ex-susp-3",
          type: "identify",
          prompt: "What are the THREE stages of a suspension?",
          correctAnswer: "Preparation, Suspension, Resolution",
          options: [
            "Preparation, Suspension, Resolution",
            "Attack, Sustain, Release",
            "Beginning, Middle, End",
            "Consonance, Dissonance, Consonance",
          ],
        },
        {
          id: "ex-susp-4",
          type: "identify",
          prompt: "Listen to this progression. How many 4-3 suspensions are there?",
          correctAnswer: "2 suspensions",
          options: ["1 suspension", "2 suspensions", "3 suspensions", "No suspensions"],
          audioPattern: ["C3", "E4", "G4", "C5", "D3", "G4", "A4", "E3", "A4", "B4", "F3", "A4", "C5", "F5"],
        },
        {
          id: "ex-susp-5",
          type: "identify",
          prompt: "Why must the suspended note be TIED or held (not re-struck)?",
          correctAnswer: "Re-striking would destroy the suspension effect",
          options: [
            "Re-striking would destroy the suspension effect",
            "It's easier to play",
            "It sounds better",
            "It's traditional",
          ],
        },
        {
          id: "ex-susp-6",
          type: "identify",
          prompt: "In which cadence did we already encounter the 4-3 suspension?",
          correctAnswer: "Compound Cadence",
          options: ["Simple Cadence", "Compound Cadence", "Double Cadence", "Deceptive Cadence"],
        },
        {
          id: "ex-susp-7-keyboard",
          type: "play",
          prompt:
            "KEYBOARD: Realize a 4-3 suspension over G-C. Bass: G-C, right hand: prepare C over G, suspend it (creating 4th), then resolve to B (3rd).",
          correctAnswer:
            "Correct realization: G-C-D over first G, then C-B-E over C (C is held/tied from previous chord)",
          hints: [
            "The C in the right hand must be HELD from the first chord (preparation) through the second chord (suspension), then resolve down to B (resolution). Don't re-strike the C!",
          ],
        },
        {
          id: "ex-susp-8-keyboard",
          type: "play",
          prompt: "KEYBOARD: Realize a Compound Cadence with 4-3 suspension. Bass: G-G-C with figures 5/4-5/3-5/3.",
          correctAnswer: "Correct realization: G-C-D over first G, G-B-D over second G (C resolves to B), then C-E-G-C",
          hints: [
            "This is the Compound Cadence you learned earlier! The C is prepared in the first chord, suspended over the second G (creating the 4th), then resolves to B (the 3rd).",
          ],
        },
        {
          id: "ex-susp-9-keyboard",
          type: "play",
          prompt: "KEYBOARD: Create a chain of 4-3 suspensions. Bass: C-D-E-F with figures 5/3-4/3-4/3-5/3.",
          correctAnswer: "Correct realization with each suspension prepared, suspended, and resolved in sequence",
          hints: [
            "Each 4-3 suspension prepares the next one. Over C: C-E-G. Over D: G (held from C) resolves to F#, creating D-F#-A. Over E: A (held) resolves to G#, creating E-G#-B. Over F: B (held) resolves to A, creating F-A-C.",
          ],
        },
        {
          id: "ex-susp-10-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a melodic line over a 4-3 suspension. Bass: G-C. Emphasize the suspension and resolution.",
          correctAnswer: "Melodic line that features the 4-3 suspension (C held over G, resolving to B over C)",
          hints: [
            "Try: C (over first G, held for 2 beats) → B (over C). This creates the characteristic 4-3 suspension. You can embellish with passing tones, but the C→B resolution should be clear.",
          ],
          bassPattern: "G3-C3",
          beatsPerNote: 4,
          tempo: 80,
        },
        {
          id: "ex-susp-11-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a melodic line over a chain of suspensions. Bass: C-D-E-F. Use the 4-3 pattern throughout.",
          correctAnswer: "Melodic line featuring multiple 4-3 suspensions in sequence",
          hints: [
            "Try: G (over C) → F# (over D) → G# (over E) → A (over F). Each note is held from the previous chord and resolves down by step, creating a chain of suspensions.",
          ],
          bassPattern: "C3-D3-E3-F3",
          beatsPerNote: 4,
          tempo: 80,
        },
      ],
      historicalContext:
        "The 4-3 suspension is the foundation of baroque counterpoint and appears in virtually every composition. It was one of the first dissonances taught to students because it follows clear rules: prepare, suspend, resolve. Fenaroli wrote: 'The student must master the 4-3 suspension before attempting any other dissonance.' The suspension creates expressive tension and was used extensively in opera, sacred music, and instrumental works. Chains of suspensions (as in Example 3) create beautiful sequential passages that appear throughout baroque music. The 4-3 suspension is also the basis for more complex suspensions like 9-8 and 7-6, which you'll learn later.",
    },
  },
  {
    id: "basic-2-romanesca",
    title: "Galant Schema: Romanesca",
    description: "Learn the descending tetrachord pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "elementary",
    level: 2,
    prerequisites: ["basic-1-simple-suspensions"],
    xpReward: 35,
    content: {
      theory:
        "The ROMANESCA is one of the oldest and most beloved patterns in Western music, appearing in countless songs, dances, and instrumental works from the Renaissance through the Baroque era. The bass descends by step: 1-7-6-5 (in C major: C-B-A-G). Above this descending bass, the upper voices create a series of consonances that give the Romanesca its characteristic sound. The standard harmonization uses: I - V6 - vi - III (or V/vi). This pattern was so common that composers could assume their audience would recognize it immediately. You'll hear it in Corelli's sonatas, Handel's arias, and countless dance movements. The beauty of the Romanesca lies in its flexibility - it can be tender and lyrical, or bold and dramatic, depending on the melodic elaboration above the bass.",
      examples: [
        {
          title: "Basic Romanesca Bass Pattern",
          description: "The fundamental descending bass: 1-7-6-5 (C-B-A-G). Listen to the stepwise descent.",
          bassPattern: "C3-B2-A2-G2",
          figuredBass: "5/3 - 6/3 - 5/3 - 5/3",
          audioPattern: ["C3", "B2", "A2", "G2"],
          beatsPerNote: 4,
        },
        {
          title: "Romanesca with Simple Harmonization",
          description: "Now hear the bass with basic chords above: I (C-E-G), V6 (B-D-G), vi (A-C-E), III (G-B-E)",
          bassPattern: "C3-B2-A2-G2",
          figuredBass: "5/3 - 6/3 - 5/3 - 5/3",
          audioPattern: ["C3", "E4", "G4", "B2", "D4", "G4", "A2", "C4", "E4", "G2", "B3", "E4"],
          beatsPerNote: 4,
        },
        {
          title: "Romanesca with Soprano Melody",
          description:
            "A flowing soprano line over the bass creates the characteristic Romanesca sound: G-F#-E-D descending",
          bassPattern: "C3-B2-A2-G2",
          figuredBass: "5/3 - 6/3 - 5/3 - 5/3",
          audioPattern: ["C3", "E4", "G4", "B2", "D4", "F4", "A2", "C4", "E4", "G2", "B3", "D4"],
          beatsPerNote: 4,
        },
        {
          title: "Extended Romanesca (Complete Octave Descent)",
          description: "The pattern continues all the way down: 1-7-6-5-4-3-2-1, creating a complete descending scale",
          bassPattern: "C3-B2-A2-G2-F2-E2-D2-C2",
          figuredBass: "5/3 - 6/3 - 5/3 - 5/3 - 6/3 - 5/3 - 7/5/3 - 5/3",
          audioPattern: [
            "C3",
            "E4",
            "G4",
            "B2",
            "D4",
            "G4",
            "A2",
            "C4",
            "E4",
            "G2",
            "B3",
            "D4",
            "F2",
            "A3",
            "C4",
            "E2",
            "G3",
            "C4",
            "D2",
            "F3",
            "B3",
            "C2",
            "E3",
            "G3",
          ],
          beatsPerNote: 4,
        },
      ],
      exercises: [
        {
          id: "rom-1",
          type: "identify",
          prompt: "What is the defining characteristic of the Romanesca bass pattern?",
          options: [
            "Ascending stepwise motion",
            "Descending stepwise motion from 1 to 5",
            "Leaping motion by fourths",
            "Repeated notes",
          ],
          correctAnswer: "Descending stepwise motion from 1 to 5",
          hints: ["Think about the direction of the bass line", "The Romanesca descends: 1-7-6-5"],
        },
        {
          id: "rom-2",
          type: "identify",
          prompt: "In C major, which notes form the Romanesca bass?",
          options: ["C-D-E-F", "C-B-A-G", "C-G-F-C", "C-E-G-C"],
          correctAnswer: "C-B-A-G",
          hints: ["The pattern descends by step", "Start on C (1) and descend to G (5)"],
        },
        {
          id: "rom-3",
          type: "identify",
          prompt: "What figured bass symbol typically appears over the second note (7) of the Romanesca?",
          options: ["5/3", "6/3", "6/4", "7/5/3"],
          correctAnswer: "6/3",
          hints: [
            "The second bass note (7) usually takes a first inversion chord",
            "First inversion is indicated by 6/3",
          ],
        },
        {
          id: "rom-4",
          type: "identify",
          prompt: "Which famous baroque composers frequently used the Romanesca pattern?",
          options: [
            "Only Italian composers",
            "Corelli, Handel, and many others across Europe",
            "Only keyboard composers",
            "It was rarely used",
          ],
          correctAnswer: "Corelli, Handel, and many others across Europe",
          hints: [
            "The Romanesca was one of the most popular patterns",
            "It appears in sonatas, arias, and dance movements throughout Europe",
          ],
        },
        {
          id: "rom-5",
          type: "identify",
          prompt: "How can the Romanesca pattern be extended beyond 1-7-6-5?",
          options: [
            "It cannot be extended",
            "Continue descending: 4-3-2-1",
            "Jump back to the beginning",
            "Ascend back up",
          ],
          correctAnswer: "Continue descending: 4-3-2-1",
          hints: [
            "The descending pattern can continue all the way to the tonic",
            "This creates a complete octave descent: 1-7-6-5-4-3-2-1",
          ],
        },
        {
          id: "rom-6",
          type: "identify",
          prompt: "What emotional character does the Romanesca typically convey?",
          options: [
            "Always sad and mournful",
            "Always bright and cheerful",
            "Flexible - can be tender, lyrical, bold, or dramatic depending on elaboration",
            "Neutral and emotionless",
          ],
          correctAnswer: "Flexible - can be tender, lyrical, bold, or dramatic depending on elaboration",
          hints: [
            "The Romanesca's character depends on how it's elaborated",
            "The same bass pattern can support many different moods",
          ],
        },
        {
          id: "rom-7-keyboard",
          type: "play",
          prompt:
            "KEYBOARD: Realize the basic Romanesca in C major. Bass: C-B-A-G. Use the harmonization: I (5/3) - V6 (6/3) - vi (5/3) - III (5/3). Write the notes you would play in the right hand for each bass note.",
          correctAnswer: "C E G, B D G, A C E, G B E (or similar voicings with these triads)",
          hints: [
            "C bass (I): play C-E-G triad",
            "B bass (V6): play B-D-G (first inversion of G major)",
            "A bass (vi): play A-C-E (A minor triad)",
            "G bass (III): play G-B-E (E major triad, or G-B-D for V)",
          ],
        },
        {
          id: "rom-8-keyboard",
          type: "play",
          prompt:
            "KEYBOARD: Realize the Romanesca in G major. Bass: G-F#-E-D. Write the notes you would play in the right hand.",
          correctAnswer: "G B D, F# A D, E G B, D F# B (or similar voicings)",
          hints: [
            "Follow the same harmonic pattern as in C major",
            "G bass (I): G-B-D triad",
            "F# bass (V6): F#-A-D (first inversion of D major)",
            "E bass (vi): E-G-B (E minor triad)",
          ],
        },
        {
          id: "rom-9-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a flowing melodic line over the Romanesca bass in C major. The bass plays C (1 bar), B (1 bar), A (1 bar), G (1 bar). Your melody should be lyrical and singable, using mostly stepwise motion with occasional leaps. Think of it as a song melody.",
          bassPattern: "C3-B2-A2-G2",
          beatsPerNote: 4,
          tempo: 80,
          correctAnswer: "Any melodic line that fits the harmony and moves gracefully",
          hints: [
            "Start on a chord tone (C, E, or G) and create a flowing line",
            "Use mostly stepwise motion for a singable melody",
            "Think of famous songs - many use this pattern!",
            "Your melody can descend with the bass or create contrary motion",
          ],
        },
        {
          id: "rom-10-melodic",
          type: "play",
          prompt:
            "MELODIES: Create a more elaborate melodic variation over the Romanesca. Use faster note values, ornaments, and more dramatic leaps. Think of a virtuoso instrumental solo.",
          bassPattern: "C3-B2-A2-G2",
          beatsPerNote: 4,
          tempo: 80,
          correctAnswer: "Any elaborate melodic line with ornaments and virtuosic elements",
          hints: [
            "Use faster rhythms - eighth notes or sixteenth notes",
            "Add ornaments like trills or turns",
            "Include some dramatic leaps for excitement",
            "Think of Corelli's violin sonatas or Handel's arias",
          ],
        },
        {
          id: "rom-11-composition",
          type: "play",
          prompt:
            "COMPOSITION: Create a complete 8-bar phrase using the extended Romanesca (1-7-6-5-4-3-2-1). This is your chance to compose a real piece! Make it musical and expressive.",
          bassPattern: "C3-B2-A2-G2-F2-E2-D2-C2",
          beatsPerNote: 4,
          tempo: 80,
          correctAnswer: "Any complete musical phrase that works with the extended Romanesca",
          hints: [
            "Think of this as composing a real piece of music",
            "Create a melody that has a clear shape - perhaps rising then falling",
            "Consider dynamics and expression - where should it be loud or soft?",
            "End with a strong cadence on the final C",
            "Listen to baroque music for inspiration - this pattern is everywhere!",
          ],
        },
      ],
      historicalContext:
        "The Romanesca appears in countless baroque compositions. Corelli used it in his violin sonatas, Handel in his arias and instrumental works, and it was a favorite of dance composers throughout Europe. The pattern was so well-known that composers could use it as a foundation for elaborate variations, knowing their audience would recognize the underlying structure. In the 18th century, every music student learned the Romanesca as one of the first compositional patterns. It appears in popular songs, courtly dances, and sophisticated chamber music alike. The pattern's flexibility made it perfect for both simple folk melodies and complex contrapuntal elaborations. When you learn the Romanesca, you're connecting with centuries of musical tradition - this is the same pattern that Mozart, Bach, and Vivaldi all knew by heart.",
    },
  },
  {
    id: "basic-3-do-re-mi",
    title: "Galant Schema: Do-Re-Mi",
    description: "Master the ascending 1-2-3 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "elementary",
    level: 2,
    prerequisites: ["basic-2-romanesca"],
    xpReward: 35,
    content: {
      theory:
        "Do-Re-Mi: 1-2-3 in the bass, often with 5-6-7 in the soprano. A simple but elegant opening pattern used in countless pieces.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "basic-4-sol-fa-mi",
    title: "Galant Schema: Sol-Fa-Mi",
    description: "Learn the descending 5-4-3 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "elementary",
    level: 2,
    prerequisites: ["basic-3-do-re-mi"],
    xpReward: 35,
    content: {
      theory: "Sol-Fa-Mi: 5-4-3 in the bass, often used as a closing pattern or to approach a cadence.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "basic-5-furno-partimenti-1",
    title: "Furno's Method: First Partimenti",
    description: "Begin with Giovanni Furno's clear, easy partimenti",
    category: "patterns",
    tradition: "italian",
    difficulty: "elementary",
    level: 2,
    prerequisites: ["basic-4-sol-fa-mi"],
    xpReward: 40,
    content: {
      theory:
        "Furno's partimenti are the perfect introduction. They combine the Rule of the Octave with simple cadences and suspensions. Each partimento is a complete musical phrase that teaches specific patterns. Start by playing the bass line, then add the right hand using the figures.",
      examples: [
        {
          id: "ex-1",
          description: "Furno Partimento No. 1 - Simple ascending scale",
          notation: "Bass: C D E F G A B C | Figures: - 6 6 - - 6 6 -",
          audioPattern: ["C3", "D3", "E3", "F3", "G3", "A3", "B3", "C4"],
          figuredBass: "- 6 6 - - 6 6 -",
        },
        {
          id: "ex-2",
          description: "Furno Partimento No. 2 - Descending with cadence",
          notation: "Bass: C B A G F E D C | Figures: - 6 6 - 6 6 7 -",
          audioPattern: ["C4", "B3", "A3", "G3", "F3", "E3", "D3", "C3"],
          figuredBass: "- 6 6 - 6 6 7 -",
        },
        {
          id: "ex-3",
          description: "Furno Partimento No. 3 - With authentic cadence",
          notation: "Bass: C D E F G C | Figures: - 6 6 - 7 -",
          audioPattern: ["C3", "D3", "E3", "F3", "G3", "C3"],
          figuredBass: "- 6 6 - 7 -",
        },
      ],
      exercises: [
        {
          id: "ex-furno-1",
          type: "play",
          prompt: "Realize this Furno partimento: Bass C-D-E-F-G-C with figures - 6 6 - 7 -",
          correctAnswer: "Correct realization with proper voice leading",
        },
      ],
      historicalContext:
        "Giovanni Furno (1748-1837) created the clearest and most pedagogical partimenti method, with written-out realizations for students to study. His 'Metodo facile, breve e chiaro' (Easy, Brief, and Clear Method) was used throughout Europe.",
    },
  },
  {
    id: "basic-6-diminution-2to1",
    title: "Simple Diminutions: 2:1 Ratio",
    description: "Learn to add two notes for every one (Ortiz style)",
    category: "diminutions",
    tradition: "both",
    difficulty: "elementary",
    level: 2,
    prerequisites: ["basic-5-furno-partimenti-1"],
    xpReward: 35,
    content: {
      theory:
        "2:1 diminution: For every note, play two. Use passing tones (stepwise motion) or neighbor tones (step away and back).",
      examples: [],
      exercises: [],
      historicalContext:
        "Diego Ortiz (1553) systematized diminution pedagogy, starting with simple 2:1 ratios before progressing to more complex divisions.",
    },
  },

  // ============================================
  // LEVEL 3: INTERMEDIATE PATTERNS
  // ============================================
  {
    id: "inter-1-prinner",
    title: "Galant Schema: Prinner",
    description: "Master the descending 6-5-4-3 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["basic-6-diminution-2to1"],
    xpReward: 45,
    content: {
      theory:
        "Prinner: 6-5-4-3 in the bass with alternating 5/3 and 6/3 chords. One of the most common opening patterns in galant music.",
      examples: [],
      exercises: [],
      historicalContext:
        "Named after Johann Jakob Prinner (1624-1694), this pattern appears in thousands of 18th-century compositions.",
    },
  },
  {
    id: "inter-2-meyer",
    title: "Galant Schema: Meyer",
    description: "Learn the 1-7-4-3 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-1-prinner"],
    xpReward: 45,
    content: {
      theory: "Meyer: 1-7-4-3 in the bass, often used as an opening riposte to the Prinner.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "inter-3-fonte",
    title: "Galant Schema: Fonte",
    description: "Master the sequential descending pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-2-meyer"],
    xpReward: 50,
    content: {
      theory:
        "Fonte: A descending sequence, typically 4-3-2-1 with specific voice leading. Creates a sense of gentle descent.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "inter-4-monte",
    title: "Galant Schema: Monte",
    description: "Learn the ascending sequential pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-3-fonte"],
    xpReward: 50,
    content: {
      theory: "Monte: An ascending sequence, the opposite of Fonte. Creates energy and forward motion.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "inter-5-ponte",
    title: "Galant Schema: Ponte",
    description: "Master the dominant pedal pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-4-monte"],
    xpReward: 50,
    content: {
      theory:
        "Ponte: A dominant pedal (sustained 5 in bass) with upper voice motion. Creates anticipation and tension.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "inter-6-german-griffe-1",
    title: "German Griffe: Basic Hand Positions",
    description: "Learn fundamental German keyboard grip patterns",
    category: "patterns",
    tradition: "german",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-5-ponte"],
    xpReward: 55,
    content: {
      theory:
        "Griffe (grips) are specific hand positions for common chord progressions. Learn the basic I-IV-V-I grip pattern.",
      examples: [],
      exercises: [],
      historicalContext:
        "Friedrich Erhardt Niedt's 'Musicalische Handleitung' (1700-1721) systematized Griffe as the foundation of German keyboard pedagogy.",
    },
  },
  {
    id: "inter-7-diminution-4to1",
    title: "Intermediate Diminutions: 4:1 Ratio",
    description: "Add four notes for every one (Ortiz/Bovicelli style)",
    category: "diminutions",
    tradition: "both",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-6-german-griffe-1"],
    xpReward: 50,
    content: {
      theory:
        "4:1 diminution: Combine passing tones, neighbor tones, and small leaps. Use consonant notes on strong beats.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "inter-8-fenaroli-book1",
    title: "Fenaroli Book I: Simple Figured Basses",
    description: "Begin Fenaroli's systematic partimenti method",
    category: "patterns",
    tradition: "italian",
    difficulty: "intermediate",
    level: 3,
    prerequisites: ["inter-7-diminution-4to1"],
    xpReward: 60,
    content: {
      theory:
        "Fenaroli Book I introduces simple figured basses without complex dissonances. Focus on smooth voice leading and proper doubling. These partimenti teach you to think harmonically while maintaining melodic lines in all voices. Prerequisites: You must know the three cadences and the Rule of the Octave before attempting Fenaroli.",
      examples: [
        {
          id: "ex-1",
          description: "Fenaroli Book I, No. 1 - Simple ascending bass",
          notation: "Bass: C D E F G A B C | Figures: - 6 6 5 - 6 6 5",
          audioPattern: ["C3", "D3", "E3", "F3", "G3", "A3", "B3", "C4"],
          figuredBass: "- 6 6 5 - 6 6 5",
        },
        {
          id: "ex-2",
          description: "Fenaroli Book I, No. 2 - With passing seventh",
          notation: "Bass: C D E F G C | Figures: - 6 6 - 7 -",
          audioPattern: ["C3", "D3", "E3", "F3", "G3", "C3"],
          figuredBass: "- 6 6 - 7 -",
        },
        {
          id: "ex-3",
          description: "Fenaroli Book I, No. 5 - Introducing suspensions",
          notation: "Bass: C F G C | Figures: - 4-3 7 -",
          audioPattern: ["C3", "F3", "G3", "C3"],
          figuredBass: "- 4-3 7 -",
        },
      ],
      exercises: [
        {
          id: "ex-fen1-1",
          type: "play",
          prompt: "Realize Fenaroli Book I, No. 1 with proper voice leading",
          correctAnswer: "Correct realization",
        },
      ],
      historicalContext:
        "Fedele Fenaroli (1730-1818) created the most thorough and detailed partimenti method, used throughout Europe for over a century. His four-book series progresses from simple figured basses to complex fugal partimenti. Book I is the foundation.",
    },
  },

  // ============================================
  // LEVEL 4: ADVANCED PATTERNS
  // ============================================
  {
    id: "adv-1-fenaroli-schema",
    title: "Galant Schema: Fenaroli",
    description: "Master the 7-1-7-1 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["inter-8-fenaroli-book1"],
    xpReward: 65,
    content: {
      theory: "Fenaroli: 7-1-7-1 in the bass with specific upper voice patterns. A sophisticated cadential approach.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-2-indugio",
    title: "Galant Schema: Indugio",
    description: "Learn the pedal point delay pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-1-fenaroli-schema"],
    xpReward: 65,
    content: {
      theory:
        "Indugio: A pedal point on 4 with 6 or 6/5 chord, delaying the cadence. Creates suspense and anticipation.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-3-jupiter",
    title: "Galant Schema: Jupiter",
    description: "Master the 1-2-4-3 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-2-indugio"],
    xpReward: 65,
    content: {
      theory: "Jupiter: 1-2-4-3 in the bass, named after Mozart's Jupiter Symphony. A majestic opening pattern.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-4-aprile",
    title: "Galant Schema: Aprile",
    description: "Learn the 4-3-7-1 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-3-jupiter"],
    xpReward: 65,
    content: {
      theory: "Aprile: 4-3-7-1 in the bass, a sophisticated cadential pattern.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-5-pastorella",
    title: "Galant Schema: Pastorella",
    description: "Master the pastoral 1-5-1 pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-4-aprile"],
    xpReward: 65,
    content: {
      theory: "Pastorella: 1-5-1 with drone bass, evoking pastoral scenes. Often in 6/8 or 12/8 time.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-6-quieszenza",
    title: "Galant Schema: Quieszenza",
    description: "Learn the 4-3-2-1 closing pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-5-pastorella"],
    xpReward: 65,
    content: {
      theory: "Quieszenza: 4-3-2-1 in the bass, a gentle closing pattern. Creates a sense of peaceful resolution.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-7-deceptive-cadence",
    title: "Galant Schema: Deceptive Cadence",
    description: "Master the V-vi surprise resolution",
    category: "schemata",
    tradition: "both",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-6-quieszenza"],
    xpReward: 60,
    content: {
      theory: "Deceptive Cadence: 5-6 instead of expected 5-1. Creates surprise and extends the phrase.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-8-evaded-cadence",
    title: "Galant Schema: Evaded Cadence",
    description: "Learn cadential evasion techniques",
    category: "schemata",
    tradition: "both",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-7-deceptive-cadence"],
    xpReward: 60,
    content: {
      theory: "Evaded Cadence: The expected cadence is avoided through various techniques, extending the phrase.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-9-passo-indietro",
    title: "Galant Schema: Passo Indietro",
    description: "Master the backward step pattern",
    category: "schemata",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-8-evaded-cadence"],
    xpReward: 65,
    content: {
      theory: "Passo Indietro: A step backward in the bass before moving forward, creating rhythmic interest.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "adv-10-german-griffe-2",
    title: "German Griffe: Sequential Patterns",
    description: "Learn Adlung's 28 sequential voice-leading patterns",
    category: "patterns",
    tradition: "german",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-9-passo-indietro"],
    xpReward: 70,
    content: {
      theory:
        "Adlung's patterns: scalar, sequential, and cadential modules. Learn to vary and recombine these formulas.",
      examples: [],
      exercises: [],
      historicalContext:
        "Jacob Adlung's 'Anweisung zum Fantasieren' (c. 1726-27) provides 28 sequential patterns with embellishments, forming the core of German improvisational training.",
    },
  },
  {
    id: "adv-11-diminution-8to1",
    title: "Advanced Diminutions: 8:1 Ratio",
    description: "Master complex diminutions (Ganassi/Bovicelli style)",
    category: "diminutions",
    tradition: "both",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-10-german-griffe-2"],
    xpReward: 70,
    content: {
      theory:
        "8:1 diminution: Complex rhythmic divisions with high proportional use. Requires advanced technique and musical taste.",
      examples: [],
      exercises: [],
      historicalContext:
        "Sylvestro Ganassi's 'La Fontegara' (1535) features the most complex diminutions of the Renaissance, with intricate rhythmic patterns.",
    },
  },
  {
    id: "adv-12-fenaroli-book2-3",
    title: "Fenaroli Books II-III: Complex Figured Basses",
    description: "Progress to more sophisticated partimenti",
    category: "patterns",
    tradition: "italian",
    difficulty: "advanced",
    level: 4,
    prerequisites: ["adv-11-diminution-8to1"],
    xpReward: 75,
    content: {
      theory:
        "Fenaroli Books II-III introduce complex suspensions, seventh chords, and chromatic passages. Requires mastery of voice leading. Book II focuses on more elaborate suspensions and dissonances. Book III introduces modulation and chromatic harmony. These partimenti prepare you for fugal writing.",
      examples: [
        {
          id: "ex-1",
          description: "Fenaroli Book II, No. 1 - Chain of suspensions",
          notation: "Bass: C F G C | Figures: - 9-8 4-3 7 -",
          audioPattern: ["C3", "F3", "G3", "C3"],
          figuredBass: "- 9-8 4-3 7 -",
        },
        {
          id: "ex-2",
          description: "Fenaroli Book II, No. 10 - Seventh chords",
          notation: "Bass: C D E F G C | Figures: 7 6/5 7 6/5 7 -",
          audioPattern: ["C3", "D3", "E3", "F3", "G3", "C3"],
          figuredBass: "7 6/5 7 6/5 7 -",
        },
        {
          id: "ex-3",
          description: "Fenaroli Book III, No. 1 - Modulation to dominant",
          notation: "Bass: C C# D Eb E F F# G | Figures: - #6 6 b6 6 6 #6 -",
          audioPattern: ["C3", "C#3", "D3", "Eb3", "E3", "F3", "F#3", "G3"],
          figuredBass: "- #6 6 b6 6 6 #6 -",
        },
      ],
      exercises: [],
      historicalContext:
        "Books II and III represent the intermediate stage of Neapolitan training. Students would spend months mastering these partimenti before progressing to Book IV. Many professional musicians never went beyond Book III.",
    },
  },

  // ============================================
  // LEVEL 5: MASTERY
  // ============================================
  {
    id: "mast-1-fenaroli-book4",
    title: "Fenaroli Book IV: Advanced Partimenti",
    description: "Master the most challenging partimenti",
    category: "patterns",
    tradition: "italian",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["adv-12-fenaroli-book2-3"],
    xpReward: 100,
    content: {
      theory:
        "Fenaroli Book IV: The pinnacle of partimenti pedagogy. Complex modulations, chromatic harmony, and sophisticated voice leading. These partimenti are essentially fugues in bass-line form. Book IV was intended only for advanced students preparing for professional careers as composers and maestri di cappella.",
      examples: [
        {
          id: "ex-1",
          description: "Fenaroli Book IV, No. 1 - Fugal partimento",
          notation: "Bass: C G C D E F G C | Figures: - - - 6 6 6/5 7 -",
          audioPattern: ["C3", "G3", "C3", "D3", "E3", "F3", "G3", "C3"],
          figuredBass: "- - - 6 6 6/5 7 -",
        },
        {
          id: "ex-2",
          description: "Fenaroli Book IV, No. 5 - Chromatic modulation",
          notation: "Bass: C C# D Eb E F F# G | Figures: - #6 6 b6 6 6 #6 -",
          audioPattern: ["C3", "C#3", "D3", "Eb3", "E3", "F3", "F#3", "G3"],
          figuredBass: "- #6 6 b6 6 6 #6 -",
        },
      ],
      exercises: [],
      historicalContext:
        "Book IV represents the highest level of Neapolitan pedagogy. Students who mastered this book were considered ready to compose operas and sacred music. Bellini, Mercadante, and other great composers studied from this book.",
    },
  },
  {
    id: "mast-2-fugal-exposition",
    title: "Fugal Improvisation: Exposition",
    description: "Learn to improvise fugal expositions",
    category: "improvisation",
    tradition: "german",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-1-fenaroli-book4"],
    xpReward: 120,
    content: {
      theory:
        "Fugal exposition: Subject, answer, countersubject. Learn the rules of tonal answers and invertible counterpoint.",
      examples: [],
      exercises: [],
      historicalContext:
        "John Mortensen's 'Improvising Fugue' (2023) revives the lost art of fugal improvisation, once a required skill for all organists.",
    },
  },
  {
    id: "mast-3-fugal-episodes",
    title: "Fugal Improvisation: Episodes",
    description: "Master sequential episodes and modulations",
    category: "improvisation",
    tradition: "german",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-2-fugal-exposition"],
    xpReward: 120,
    content: {
      theory: "Episodes: Sequential passages that modulate to new keys. Use fragments of the subject in sequence.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "mast-4-imitazione",
    title: "Imitazione: Imitative Counterpoint",
    description: "Learn Italian imitative improvisation techniques",
    category: "improvisation",
    tradition: "italian",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-3-fugal-episodes"],
    xpReward: 120,
    content: {
      theory:
        "Imitazione: Free imitative counterpoint without strict fugal rules. More flexible and expressive than German fugue.",
      examples: [],
      exercises: [],
    },
  },
  {
    id: "mast-5-free-improvisation",
    title: "Free Improvisation: Combining All Elements",
    description: "Improvise freely using all learned patterns and techniques",
    category: "improvisation",
    tradition: "both",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-4-imitazione"],
    xpReward: 150,
    content: {
      theory:
        "Free improvisation: Combine schemata, diminutions, Griffe, and fugal techniques into coherent musical statements. The ultimate goal of baroque training.",
      examples: [],
      exercises: [],
      historicalContext:
        "In the baroque era, all professional musicians were expected to improvise. Handel, Bach, Mozart, and Beethoven were renowned for their improvisational abilities.",
    },
  },
  {
    id: "mast-6-durante-partimenti",
    title: "Durante's Diminished Partimenti",
    description: "Master Francesco Durante's sophisticated partimenti",
    category: "patterns",
    tradition: "italian",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-1-fenaroli-book4"],
    xpReward: 120,
    content: {
      theory:
        "Francesco Durante (1684-1755) was the most influential teacher at the Neapolitan conservatories. His partimenti are more sophisticated and chromatic than Fenaroli's, with extensive use of diminished harmonies and complex voice leading. Durante taught Pergolesi, Paisiello, Piccinni, and many other great composers.",
      examples: [
        {
          id: "ex-1",
          description: "Durante Partimento - Diminished seventh chains",
          notation: "Bass: C B Bb A Ab G | Figures: - 6/5 6/5 6/5 6/5 -",
          audioPattern: ["C3", "B2", "Bb2", "A2", "Ab2", "G2"],
          figuredBass: "- 6/5 6/5 6/5 6/5 -",
        },
      ],
      exercises: [],
      historicalContext:
        "Durante's partimenti represent the highest level of Neapolitan sophistication. His students dominated Italian opera for generations.",
    },
  },
  {
    id: "mast-7-insanguine-rules",
    title: "Insanguine's Rules and Partimenti",
    description: "Study Giacomo Insanguine's systematic approach",
    category: "patterns",
    tradition: "italian",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-6-durante-partimenti"],
    xpReward: 120,
    content: {
      theory:
        "Giacomo Insanguine (1728-1795), known as 'Monopoli', created a comprehensive rulebook that systematizes all the patterns of Neapolitan pedagogy. His partimenti are clear and methodical, making them excellent for understanding the underlying principles.",
      examples: [],
      exercises: [],
      historicalContext:
        "Giacomo Insanguine (1728-1795), known as 'Monopoli', created a comprehensive rulebook that systematizes all the patterns of Neapolitan pedagogy. His systematic approach helps students understand WHY patterns work, not just HOW to play them.",
    },
  },
  {
    id: "mast-8-sala-treatise",
    title: "Nicola Sala's Theoretical Rules",
    description: "Master the theoretical foundations with Sala",
    category: "patterns",
    tradition: "italian",
    difficulty: "mastery",
    level: 5,
    prerequisites: ["mast-7-insanguine-rules"],
    xpReward: 120,
    content: {
      theory:
        "Nicola Sala (1713-1801) wrote the most comprehensive theoretical treatise on partimenti. His 'Regole del Contrappunto Pratico' (Rules of Practical Counterpoint) explains the theoretical basis for all the patterns you've learned.",
      examples: [],
      exercises: [],
      historicalContext:
        "Nicola Sala (1713-1801) wrote the most comprehensive theoretical treatise on partimenti. His 'Regole del Contrappunto Pratico' (Rules of Practical Counterpoint) explains the theoretical basis for all the patterns you've learned. Sala's treatise was the standard textbook at the Neapolitan conservatories and explains the 'why' behind every rule and pattern.",
    },
  },
]

export const SKILL_LEVELS = [
  { level: 1, name: "Novice", xp: 0, xpRequired: 100 },
  { level: 2, name: "Apprentice", xp: 0, xpRequired: 300 },
  { level: 3, name: "Student", xp: 0, xpRequired: 600 },
  { level: 4, name: "Practitioner", xp: 0, xpRequired: 1200 },
  { level: 5, name: "Journeyman", xp: 0, xpRequired: 2400 },
  { level: 6, name: "Master", xp: 0, xpRequired: 4800 },
  { level: 7, name: "Virtuoso", xp: 0, xpRequired: 9600 },
]

// Helper functions for curriculum navigation
export function getLessonById(id: string): Lesson | undefined {
  return CURRICULUM.find((lesson) => lesson.id === id)
}

export function getLessonsByLevel(level: number): Lesson[] {
  return CURRICULUM.filter((lesson) => lesson.level === level)
}

export function getLessonsByTradition(tradition: "italian" | "german" | "both"): Lesson[] {
  return CURRICULUM.filter((lesson) => lesson.tradition === tradition || lesson.tradition === "both")
}

export function getNextLesson(currentLessonId: string, completedLessonIds: string[]): Lesson | null {
  const currentIndex = CURRICULUM.findIndex((l) => l.id === currentLessonId)
  if (currentIndex === -1) return CURRICULUM[0] // Start from beginning

  // Find next lesson where all prerequisites are completed
  for (let i = currentIndex + 1; i < CURRICULUM.length; i++) {
    const lesson = CURRICULUM[i]
    const allPrereqsMet = lesson.prerequisites.every((prereq) => completedLessonIds.includes(prereq))
    if (allPrereqsMet) return lesson
  }

  return null // No more lessons available
}

export function getAvailableLessons(completedLessonIds: string[]): Lesson[] {
  return CURRICULUM.filter((lesson) => {
    const allPrereqsMet = lesson.prerequisites.every((prereq) => completedLessonIds.includes(prereq))
    const notCompleted = !completedLessonIds.includes(lesson.id)
    return allPrereqsMet && notCompleted
  })
}
